apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-g0au
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-g0au
    app.kubernetes.io/part-of: ci10t-786-0077-app
  name: devfile-sample-g0aul4xz
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-g0au
    weight: null
status: {}
